---
AWSTemplateFormatVersion: '2010-09-09'
Description: Launch a Linux instance and install Crowdstrike and
  attach IAM role to EC2 instance for CS installation
  Version 3.4
Metadata:
  Stack:
    Value: 0
  VersionDate:
    Value: 20190725
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in the stack
  Output:
    Description: N/A
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: EC2 Instance Configuration
      Parameters:
      - AccountOU
      - VPC
      - AMI
      - InstanceType
      - DiskSize
      - DiskType
      - Subnet
      - ExistingSecurityGroupID
      - KeyPair      
    - Label:
        default: Tag Information
      Parameters:
      - TagName
      - TagLinuxServerName
      - TagBackup
      - TagPatched
      - TagOwner
      - TagFunction
      - TagOS
      - TagOSVersion
    ParameterLabels:
      AccountOU:
        default: Account OU
      VPC:
        default: VPC ID
      AMI:
        default: Amazon Machine Image
      InstanceType:
        default: Instance Type
      DiskSize:
        default: System Partition Size
      DiskType:
        default: System Partition Type
      Subnet:
        default: Instance Subnet
      ExistingSecurityGroupID:
        default: Subnet Security Group
      KeyPair:
        default: Access Key Pair      
      TagName:
        default: Name
      TagLinuxServerName:
        default: Linux Server Name
      TagBackup:
        default: Backup
      TagOwner:
        default: Owner
      TagPatched:
        default: Patched
      TagFunction:
        default: Function
      TagOS:
        default: Operating System
      TagOSVersion:
        default: Operating System Version

Parameters:
  InstanceProfileName:
    Description: IAM instance profile name to attach to the EC2 instance
    Type: String
    AllowedValues:
      - s3-bucket-role-cs
      - InstanceRoleForAmazonSSM
    Default: InstanceRoleForAmazonSSM
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Select the VPC to place this instance
  AMI:
    Type: String
    Description: Select a Linux Amazon Machine Image for this Instance
    AllowedValues:
    - Amazonlinux2023
    - Amazonlinux2
  InstanceType:
    Type: String
    Description: Select the Instance Type
    Default: t2.micro
    AllowedValues:
    - t2.micro
    - t2.small
    - t2.medium
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m5.xlarge
    - c1.medium
    - c1.xlarge
    - c3.large
    - c3.xlarge
    - c3.2xlarge
    - c3.4xlarge
    - c3.8xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c4.4xlarge
    - c4.8xlarge
    - g2.2xlarge
    - r3.large
    - r3.xlarge
    - r3.2xlarge
    - r3.4xlarge
    - r3.8xlarge
    - i2.xlarge
    - i2.2xlarge
    - i2.4xlarge
    - i2.8xlarge
    - d2.xlarge
    - d2.2xlarge
    - d2.4xlarge
    - d2.8xlarge
    - hi1.4xlarge
    - hs1.8xlarge
    - cr1.8xlarge
    - cc2.8xlarge
    - cg1.4xlarge
    ConstraintDescription: Must be a valid EC2 instance type.
  Subnet:
    Type: AWS::EC2::Subnet::Id
    Description: Select a Subnet to place this instance
  ExistingSecurityGroupID:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Select a Security Group to place this instance
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select a KeyPair for this EC2 Instance
  TagName:
    Description: Enter the Name of the EC2 instance
    Type: String
    Default: Name
  TagLinuxServerName:
    Description: Enter Linux Server Name
    Type: String
    Default: Linux
  TagBackup:
    Description: Is the Instance being backed up (Yes or No)
    Type: String
    Default: Yes
  TagOwner:
    Description: Enter the Team/Owner of this Instance (eg. Energy Services, Smart Buildings)
    Type: String
    Default: Team/Owner Name?
  TagFunction:
    Description: Enter the function of the EC2 instance (Monitoring Server)
    Type: String
    Default: Monitoring Server
  TagOS:
    Description: Enter the Operating System of the EC2 instance
    Type: String
    Default: Linux
  TagOSVersion:
    Description: Enter the version of Operating System
    Type: String
    Default: Amazon Linux 2023
  TagPatched:
    Description: Is the instance being Patched
    Type: String
    Default: Yes
Mappings:
  RegionAMIMap:
    eu-west-1:
      Amazonlinux2023: ami-0e309a5f3a6dd97ea
      Amazonlinux2: ami-0a1f6cc8163bdcc75
    eu-west-2:
      Amazonlinux2023: ami-0cf6f2b898ac0b337
      Amazonlinux2: ami-06d0baf788edae448
Resources:
  myEC2InstanceSSM:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile:
        Ref: InstanceProfileName
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo mkdir /mount
            sudo mkdir ~/.aws
            cat <<'EOF' >> ~/.aws/config
            [profile s3-bucket-role-cs]
            role_arn = arn:aws:iam::877968844667:role/s3-bucket-role-CS
            credential_source = Ec2InstanceMetadata
            EOF
            sudo aws s3 cp s3://crowdstrikeinstalls/falcon-sensor-7.03.0-15805.amzn2023.x86_64.rpm /mount --profile s3-bucket-role-cs
            sudo yum -y install ./mount/falcon-sensor-7.03.0-15805.amzn2023.x86_64.rpm
            sudo /opt/CrowdStrike/falconctl -s --cid=C78902F9C85144558CFCCBC3A21AF3C9-75 --tags=LocalIT
            sudo service falcon-sensor start
            sudo systemctl start falcon-sensor
      KeyName:
        Ref: KeyPair
      ImageId: !FindInMap
        - RegionAMIMap
        - Ref: 'AWS::Region'
        - Ref: AMI
      InstanceType:
        Ref: InstanceType
      Tags:
      - Key: Name
        Value: !Ref TagName
      - Key: Linux Server Name
        Value: !Ref TagLinuxServerName
      - Key: Backup
        Value: !Ref TagBackup
      - Key: Patched
        Value: !Ref TagPatched
      - Key: Owner
        Value: !Ref TagOwner
      - Key: Function
        Value: !Ref TagFunction
      - Key: OS
        Value: !Ref TagOS
      - Key: OS Version
        Value: !Ref TagOSVersion
      SubnetId:
        Ref: Subnet
      SecurityGroupIds:
      - Ref: ExistingSecurityGroupID
